services:
  onos: 
    image: onosproject/onos:2.7-latest
    container_name: onos
    hostname: onos
    privileged: true
    networks:
      onos-net:
        ipv4_address: 192.168.100.2
    environment:
      - ONOS_APPS=openflow,fpm,gui2,fwd,router
    ports:
      - "2620:2620"  
      - "8181:8181"
      - "8101:8101"
      - "6653:6653"
    tty: true
    stdin_open: true

  h1:
    image: host
    container_name: h1
    privileged: true
    build: 
      context: .
      dockerfile: host.Dockerfile
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    entrypoint: ["bin/sh", "-c"]
    command:
    - |
      ip route del default
      sleep infinity
  h2:
    image: host
    container_name: h2
    privileged: true
    build: 
      context: .
      dockerfile: host.Dockerfile
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    entrypoint: ["bin/sh", "-c"]
    command:
    - |
      ip route del default
      sleep infinity
  R1:
    image: frrouting/frr-debian
    container_name: R1
    hostname: R1
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    networks:
      onos-net:
        ipv4_address: 192.168.100.3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./config/daemons:/etc/frr/daemons
      - ./config/R1/frr.conf:/etc/frr/frr.conf
  R2:
    image: frrouting/frr-debian
    container_name: R2
    hostname: R2
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./config/daemons:/etc/frr/daemons
      - ./config/R2/frr.conf:/etc/frr/frr.conf

networks:
  onos-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
