services:
  onos:
    image: onosproject/onos:2.7-latest
    container_name: onos
    privileged: true
    environment:
      - ONOS_APPS=openflow,fpm,gui
    ports:
      - "2620:2620"
      - "8181:8181"
      - "8101:8101"
      - "6653:6653"
    tty: true
    stdin_open: true
  
  h1:
    image: sdnfv-final-host
    container_name: h1
    privileged: true
    network_mode: "none"
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - SYS_MODULE
    command:
    - |
      sleep infinity

  h2:
    image: sdnfv-final-host
    container_name: h2
    privileged: true
    network_mode: "none"
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - SYS_MODULE
    command:
    - |
      sleep infinity
  R1:
    image: sdnfv-final-frr
    container_name: R1
    hostname: R1
    privileged: true
    network_mode: "none"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - SYS_MODULE
    volumes:
      - ./config/daemons:/etc/frr/daemons
      - ./config/R1/frr.conf:/etc/frr/frr.conf

  R2:
    image: sdnfv-final-frr
    container_name: R2
    hostname: R2
    privileged: true
    network_mode: "none"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - SYS_MODULE
    volumes:
      - ./config/daemons:/etc/frr/daemons
      - ./config/R2/frr.conf:/etc/frr/frr.conf

